### ISSUE TITLE
Pip install doesnt work

### ISSUE THREAD

**Issue by jmosbacher** [AxFoundation/strax#105]
pip install strax fails with following Error:

> Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "/tmp/pip-install-7_x2ss78/strax/setup.py", line 4, in <module>
>        with open('requirements.txt') as f:
>    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

Current MANIFEST.in file seems fine so maybe version on PyPI is outdated?

**Comment by JelleAalbers** [comment]
Thanks for reporting, probably this is what Chris tried to fix in https://github.com/AxFoundation/strax/commit/0fbe63a17dce39283f3cd02a7eb2f63489e0c90d. So hopefully the next release, when it autodeploys to pypi, should fix it. There will be one next week for the XENON split. 

In the meantime, you can do a editable/developer installation (`git clone https://github.com/AxFoundation/strax.git`, `pip install -e strax`).

**Comment by jmosbacher** [comment]
pymongo seems to be requirement but missing from the requirements.txt, is this a bug or feature?

**Comment by jmosbacher** [comment]
oh, its in the xenon distro. nevere mind.

**Comment by JelleAalbers** [comment]
Pip install works now (straxen's readthedocs build is using it), so it seems Chris' fix worked.
