### ISSUE TITLE
Bug: cannot import strax

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#12]
There's some issue with caching in numba?  The versions of all packages are as pinned in the requirements.txt.  When I do 'import strax', I get:

> RuntimeError: cannot cache function 'sort_by_time': no locator available for file '/Users/tunnell/Work/anaconda/envs/strax/lib/python3.6/site-packages/strax-0.0.1-py3.6.egg/strax/utils.py'

See the full output in https://gist.github.com/tunnell/594018c76e83f751bd8612fa22c099f2

Here is the result of `pip freeze` https://gist.github.com/tunnell/e4a6e1590a3edd9c604c52b4126119fe

**Comment by tunnell** [comment]
This happens if you run python in any directory other than the strax directory.

**Comment by tunnell** [comment]
This means example notebooks don't work from where they are.

**Comment by tunnell** [comment]
Even after creating `~/.cache/numba`

**Comment by JelleAalbers** [comment]
I've never seen this on Travis, my laptop, or my windows PC. It's probably related to https://github.com/JelleAalbers/strax/blob/master/strax/utils.py#L11 somehow, but still interesting.
