### ISSUE TITLE
Test data missing

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#13]
There's test data for strax e.g. test_records_uncomp.json.  However, this isn't in the repository.

**Comment by JelleAalbers** [comment]
Yes, it should go in git lfs or more likely a link to the xenon wiki/midway (since I can't just spread around XENON1T raw data). In the future we should simulate some data or just ask if it's ok to distibute 10 sec of data (that's already ~300 MB, more than enough to test).

**Comment by JelleAalbers** [comment]
I've put it on midway for now at `/home/aalbers/strax_test_data`, just drop both files in the `notebooks` dir
