### ISSUE TITLE
Hit area not computed before being used

### ISSUE THREAD

**Issue by darrylmasson** [AxFoundation/strax#141]
In `peak_building.find_peaks` the area of a peak is calculated from the hits that make it up, but `pulse_processing.find_hits` doesn't compute hit area, so the area of a peak is going to be zero (potentially a problem if a nonzero minimum peak area is specified).

**Comment by JelleAalbers** [comment]
Thanks for spotting this @darrylmasson! We should either compute the hit area or not track it. 

Hits are not used as much in straxen as in pax. A peak is simply a time range: unlike in pax, peaks cannot overlap. We zero the PMT waveforms outside hits in https://github.com/XENONnT/straxen/blob/master/straxen/plugins/plugins.py#L140, and again use hits for the initial clustering step. But after that, hit info is ignored. If a peak is split  and the n_hits number becomes meaningless.
