### ISSUE TITLE
Numba cache-related problem with split peaks

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#180]
Sometimes during processing numba throws an internal error in one of the peak splitting functions. Removing all `__pycache__` folders from the strax (and perhaps also straxen) directory works around the problem.

One condition in which I think I saw this is when I start strax in multiprocessing mode the first time it is installed. Then likely the multiple processes might start independent numba compilations that interfere with each other while writing to the cache. However @jhowl01 also saw this without using multiprocessing, so there are likely multiple causes.

**Comment by JelleAalbers** [comment]
I still see this problem occasionally, even when not using multiprocessing. Just removing strax/processing/__pycache__ and restarting the kernel resolves the problem, however.

**Comment by jorana** [comment]
Seems solved
