### ISSUE TITLE
Zenodo badge does not update

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#220]
The zenodo badge added by @tunnell in #58 works, but does not update each release. Itl refers to 0.3.0 currently while we're at 0.8.1. Can we make this auto-update or do we have to change it manually as part of the release procedure?

**Comment by jorana** [comment]
Fixed in https://github.com/AxFoundation/strax/commit/9c023b0d6a31743dc5a4f2c96b8c79cebde4b19e
