### ISSUE TITLE
Containment options for LoopPlugin, documentation

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#221]
Prompted by a question from @lucasdevries:

Currently LoopPlugin only returns things fully contained in the larger things. For example, if you loop over peaks in an event, you only get the peaks that are completely in the event, not peaks that are partially in it. Or, if you loop over records in a peak, you only get the records that are completely in the peak, not those that contribute to it but have some part outside it.

We should also allow users to loop over all small things that touch a bigger thing. For get_data and get_array this is already implemented using the `time_selection='touching'` option.

Also, LoopPlugin should have documentation :-)

**Comment by jorana** [comment]
Started with the documentation in:
https://github.com/AxFoundation/strax/pull/274 commit 9182f1b 

For resolving this issue I'll prepare another PR.

**Comment by jorana** [comment]
Should be easy by changing this line:
https://github.com/AxFoundation/strax/blob/164a25239ef08b3dad5ddd958d1d404b776a163a/strax/plugin.py#L665

**Comment by jorana** [comment]
Fixed in #424
