### ISSUE TITLE
Deterministic/pinned test environment

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#229]
Strax is a library that should support a wide range of dependency versions. Still, it would be good to run the integration tests against a specific set of pinned dependencies. This gives a known-good configuration and prevents sudden build failures due to breaking updates upstream.

@tunnell implemented this a while ago, with PyUP keeping the dependencies up to date. Since then some things have changed: PyUP seems to have died, and we made a new repository [base_environment](https://github.com/XENONnT/base_environment) to host a deterministic environment for XENON.

We have a few options:
  * Switch to [dependabot](https://dependabot.com/) just like [base-environment](https://github.com/XENONnT/base_environment/pull/48). Unfortunately, that means we'll get two sets of 5-10 pull request updates a week. If we do the same for other repos like straxen and wfsim we'll have three or four sets of them.
  * Fetch the pins from base_environment's [requirements.txt](https://github.com/XENONnT/base_environment/blob/master/requirements.txt) during continuous integration.
  * Rethink thinks more fundamentally and investigate the new generation of python packaging and dependency resolution tools, like pipfile locks, pipenv, poetry, etc.

**Comment by jorana** [comment]
Hi Jelle,
I think the first option has also fundamental issues that it will prohibit the  base_env from actually using dependabot successfully. If we fix everything here, it will become difficult for the base_env to fix the more complex dependencies.

**Comment by JelleAalbers** [comment]
Good point Joran, I guess this relates to your question at https://github.com/XENONnT/base_environment/issues/404. 

Maybe the easiest fix is the second option then, i.e. have a small script run during strax's travis build:
  * wget/curl https://raw.githubusercontent.com/XENONnT/base_environment/master/requirements.txt,
  * parse it with e.g. https://pypi.org/project/requirements-parser
  * same for strax's requirements.txt,
  * Output a new requirements.txt with strax's requirements and the version pins from base_environment (if any, and if the strax branch being built specifies a version pin in the requirements.txt, that should take precedence) 
  * Then you'd install the new requirements.txt here https://github.com/AxFoundation/strax/blob/master/.travis.yml#L46 and proceed with the build as normal

**Comment by jorana** [comment]
Hi Jelle, yeah thanks I was thinking something similar, perhaps slightly less elegant but brutely simple:
```bash
# Get requirements from the base_env
wget -O pre_requirements.txt https://raw.githubusercontent.com/XENONnT/base_environment/master/requirements.txt
# Select requirements for troublesome modules and install
cat pre_requirements.txt | grep 'numpy\|numba\|tensorflow\|blosc' &> pre_requirements.txt
pip install -r pre_requirements.txt
```

**Comment by jorana** [comment]
With #383 this issue should be fixed
