### ISSUE TITLE
Document 'context'

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#23]
Hey, since this is a quite important function, can we document the Context() constructor better?  It's one of the first steps to doing anything interesting.

https://github.com/AxFoundation/strax/blob/master/strax/core.py#L39

**Comment by JelleAalbers** [comment]
Good point; see also the demo notebooks at https://github.com/AxFoundation/strax/blob/master/notebooks/Strax%20demo.ipynb for a few practical examples
