### ISSUE TITLE
Problems with time range selection

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#230]
In the latest version of straxen @tunnell and @aladinggit caught a problem with the time range selection, as used for the waveform plotting (https://github.com/XENONnT/straxen/issues/48#issuecomment-584316043). This is most likely due to the recent change https://github.com/AxFoundation/strax/commit/5f795afecc6d2d05109cc50f590cc7ff1fe5f303.

**Comment by JelleAalbers** [comment]
@tunnell @aladinggit Could you see if your issue is resolved in v0.8.8? I deployed it to the backup environment.

**Comment by tunnell** [comment]
The backup environment is the conda environment on dali?

**Comment by JelleAalbers** [comment]
The time range selection code has been completely rewritten (and much simplified) in https://github.com/AxFoundation/strax/pull/235. Let's make a new issue if one arises.
