### ISSUE TITLE
In-rundoc defaults makes availability check slow

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#246]
The defaults-in-the-rundoc introduced in https://github.com/AxFoundation/strax/pull/223 make the data availability check very slow. For every run we currently send out a separate run metadata query to even be able to check if a piece of data is available. The result should be cached for each run, but it is still very inefficient.

There are (at least) two possible solutions:
  * Add a method to storage frontends to quickly retrieve run defaults for many runs. Databases can easily do this, for json files it won't be any faster than what we currently do.
  * Remove support for in-rundoc defaults. They aren't used yet and maybe there were a bad idea to begin with.

**Comment by jorana** [comment]
I don't think this is ever used and may be obsolete due to CMT

**Comment by jorana** [comment]
Fixed in #440
