### ISSUE TITLE
Saturated channel not counted

### ISSUE THREAD

**Issue by zhut19** [AxFoundation/strax#256]
The saturated channel is rewritten to 0 while looping over records coming after the saturated pulse.

https://github.com/AxFoundation/strax/blob/2146f9e6488441c52a789fad68cbed71468f3ced/strax/processing/peak_building.py#L211

This line might need to be changed to 
`p['saturated_channel'][ch] |= int(max_in_record >= r['baseline']) `

**Comment by JelleAalbers** [comment]
Good catch, feel free to make a PR

**Comment by JelleAalbers** [comment]
Thans for reporting, this should now be fixed as part of #260; feel free to reopen if it does not work
