### ISSUE TITLE
flip =False condition will cause records to go to 0

### ISSUE THREAD

**Issue by sophiaandaloro** [AxFoundation/strax#265]
We define `flip` as a Boolean, True if we flip the records when subtracting baseline, False if not flipped. However, in performing the flip here:
https://github.com/AxFoundation/strax/blob/8e94cd95d823c1537cd49a568d8a3ee4e0204ea5/strax/processing/pulse_processing.py#L68-L69
If we set `flip=False`, this seems to set `d['data']` equal to all zeros, as `(-1 * False)=0`. 
Typically we have flip=True but this could be an issue for anyone trying to look at unflipped records. 
Unless I am missing something, I will propose a change, just wanted to confirm this is an issue first.

**Comment by sophiaandaloro** [comment]
my solution: change L68-69 to the following: 
```
d['data'][:d['length']] = (
              np.where(flip, -1, 1)  *  (d['data'][:d['length']] - int(bl)) )

```

**Comment by sophiaandaloro** [comment]
PR: https://github.com/AxFoundation/strax/pull/266

**Comment by JelleAalbers** [comment]
Closing since #266 is merged
