### ISSUE TITLE
License file and cookie cutter

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#3]
You should look at cookie-cutter to see the standard files for a Python project re: testing and the rest.  Also, at very least add a license file so others know how to use it.

**Comment by JelleAalbers** [comment]
Yes, we need most of these things. I preferred starting with an empty package so I could add only the things I needed and understood, though it will be a bit more work.

 - [ ] License
 - [ ] TravisCI
 - [ ] Sphinx module autodocs
 - [ ] .. and host them on readthedocs
 - [ ] Bump version to 0.1.0
 - [ ] Pypi

After these basics we might want other hooks too (e.g. #5, coveralls, a linter, ...).

**Comment by tunnell** [comment]
For running test notebooks :) https://mybinder.org

**Comment by tunnell** [comment]
Mostly solved, stale.
