### ISSUE TITLE
Remove S3 and Mongo backends

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#307]
At least the S3 one, I wrote and isn't used.  I doubt it works.  Backends that aren't tested automatically or understood, should be removed.  Objections?  People can always fetch out of version control.

**Comment by jorana** [comment]
I'm okay with removing S3, mongo we should start using somewhere soon to log things like pulse_counts.

**Comment by jorana** [comment]
Removal of S3 is initiated in #344

**Comment by jorana** [comment]
With #358 in the pipeline I'm closing this issue
