### ISSUE TITLE
dtype_for is super misleading for the user.

### ISSUE THREAD

**Issue by WenzDaniel** [AxFoundation/strax#313]
The function dtype_for() of the Plugin class is super misleading for users. They see its usage like in here  https://github.com/XENONnT/straxen/blob/56abca546b2e6f31ff3a49b04513cd6ba3fe00bb/straxen/plugins/peaklet_processing.py#L116

In case of an multi-output plugin it will return the dtype of the specified output. In case of a regular plugin it will just return the dtype of the plugins provides. However the function looks like you could call any dtype simply by specifying its "provides" name.

**Comment by jorana** [comment]
I think the first thing to do would be adding a docstring. Perhaps we could add a renamed function that redirects to this function to prevent incompatibility. We could throw a deprecation warning and delete the function after a given time.

**Comment by jorana** [comment]
I think #344 sufficiently addresses this. It makes actually quite a lot of sense that the plugin object cannot just provide a dtype for something it does not know about.
