### ISSUE TITLE
New mongo versions projection rules cause Path collision errors

### ISSUE THREAD

**Issue by jmosbacher** [AxFoundation/strax#324]
Following a slack discussion:
From version 4.4 onward it is not allowed to project a field and its subfield in a single query. Since strax adds some fields to the projections here:
   ```
   store_fields = tuple(set(
        list(strax.to_str_tuple(store_fields))
        + ['name', 'number', 'tags', 'mode',
           strax.RUN_DEFAULTS_KEY]
        + list(self.context_config['store_run_fields'])))
    check_available = tuple(set(
        list(strax.to_str_tuple(check_available))
        + list(self.context_config['check_available'])))
```
which makes it impossible to replace a default field with a subfield of that field from the context parameter.

To replicate the old mongo behavior, strax should only add default fields for which none of the sub fields are requested in the context. Something like:
```
default_fields = ['name', 'number', 'tags', 'mode',
           strax.RUN_DEFAULTS_KEY] + list(strax.to_str_tuple(store_fields))
explicit_fields = [field.split(".")[0] for field in self.context_config['store_run_fields']]
extra_fields = [x for x in default_fields if x not in explicit_fields]
   store_fields = tuple(set(    
        + extra_fields
        + list(self.context_config['store_run_fields'])))
    check_available = tuple(set(
        list(strax.to_str_tuple(check_available))
        + list(self.context_config['check_available'])))
```
Or something more elegant

**Comment by jorana** [comment]
As you pointed out in #325 it would be good to also add some automatized tests for this.

**Comment by jorana** [comment]
This seems fixed and mostly on the `straxen` side. I don't think it's worth keeping the issue open as a reminder that we need to add tests to the mongo interfaces. Feel free to reopen.
