### ISSUE TITLE
Remove estimate_run_start in next release

### ISSUE THREAD

**Issue by WenzDaniel** [AxFoundation/strax#337]
estimate_run_start was replaced by estimate_run_start_and_end in https://github.com/AxFoundation/strax/pull/318

**Comment by jorana** [comment]
@WenzDaniel , I don't think we need to rush. The code is easy to maintain and having both function is not a problem bad enough that we should have scripts/notebooks crashing because of it. Let's keep the deprecation warning in there and in the distant future indeed remove it
