### ISSUE TITLE
Mongo registry may become large

### ISSUE THREAD

**Issue by jorana** [AxFoundation/strax#346]
In commit https://github.com/AxFoundation/strax/commit/107b2b8c92da455544d04fd517d91f0c8339c9f7 we have changed the building of the plugin class registry. With this we offload queries to the database because the data is only queried once (and then stored in the `chunks_registry`.

Potentially, this might start taking a lot of data as one is querying all of the runs in the collection. We could opt to clear this `chunks_registry` if it exceeds a max number by clearing it if 
```python
sys.getsizeof(self.chunks_registry)/1e6>MAX_BUFF_MB
```

I don't think this is much of an issue as the data itself is very small but we could keep this in mind. @darrylmasson , strong opinions?

**Comment by darrylmasson** [comment]
I see a couple of potential frustrations for an analyst, mainly around how many runs would fit into `MAX_BUFF_MB`. If this is "small", then they might have to frequently wait while the database is queried and the registry rebuilt, if they don't have decent caching in their notebook. Dictionaries remember the order in which keys are inserted, correct? What if the cache isn't strictly cleared when reaching this size threshold, but we start by clearing the earliest entries?

**Comment by jorana** [comment]
So in principle, it's not at all slow if we rebuild the ``chunks_registry`` taking ~a few seconds per run (more or less implied by the 16 MB doc-limit). But yeah, it should be at least larger than the size of a single run, otherwise we might be rebuilding it more than once for a given run which would utterly slow things down.

I like the idea of ` we start by clearing the earliest entries`. We can set a default value of e.g. 500 MB (i.e. just over 2 chunks of other regular data). At the moment a single run Online Monitor -data is ~45 MB for a one hour run. As such we would be able to cache 12 runs.

**Comment by darrylmasson** [comment]
Here's a slightly wilder idea: what if we set the cache to a certain number of runs, rather than MB?

**Comment by jorana** [comment]
Possible, but imagine we are loading the veto_intervals which is only ~O(kB). Here you could cache all of the data that is stored in the collection without any memory issues. The number of runs is not per se a factor that hampers your notebook from not dying, it's the memory you are using. 

A combination of both is of course also possible: first check if we have exceeded 500 MB, then, if there are more than 5 runs cashed in the _backend_, clear the buffer. This of course does not hamper the analyst from using the data (one has obtained this already in st.get_array/df). It's just the backend-buffer that is sitting otherwise idle in the background eating your RAM that needs clearing.

**Comment by darrylmasson** [comment]
Ok so here's another thought: why are we even caching? Reading from the database isn't massively more expensive than going back to disk to retrieve a chunk, and the file system front/backends don't cache. When the user asks the context for data, it should go to the database, read it, and return it to the user, not keep around, silently chewing up memory forever. It should be the user's responsibility to ensure that they cache data they request from the context. Yes, insert comment here about users and not caching like they should, but still.

**Comment by jorana** [comment]
So we are cashing because doing a `find_one` for each chunk takes more time than just doing a `find` operation for all of the chunks.

Cashing per run -> reading from the database is still much more expensive than reading from a file. As we have discussed offline the database is slower than one would expect. Also, cashing for this particular backend may not be as trivial as it sounds, if you are running with `allow_incomplete=True` you might start cashing incomplete runs which I guess most users won't be getting right.

> silently chewing up memory forever. 

Indeed, I agree, it's why I opened this issue in the first place to discuss.

So the options are:
1. Cache max 1 run
2. Cache max x MB
3. Cache max x MB, and max y runs
4. Do some magic trying to override the `loader` (https://github.com/AxFoundation/strax/blob/master/strax/storage/common.py#L372) to clear the buffer as soon as one runs has been loaded. Thereby never keeping a registry around. I'm not looking forward to figuring this out ;) but it's not impossible. For the collections we have in nT it really makes no difference as this 45 MB is not going to hurt you much.

I'm liking 3 because it's faster and offloads the database especially if people make looped queries. On the other hand there is for sure something to say about making the code lean and don't start causing unexpected memory issues whereof the user has no idea if it works. I can revert to option 1.

**Comment by darrylmasson** [comment]
I'd vote for 3, and if this causes issues we start looking into 4.

**Comment by jorana** [comment]
Thanks Darryl, I'm going to set it to 200 MB & 5 runs then. Feel free to disagree. The 500 MB I mentioned earlier is rather generous for memory that isn't accessed.

**Comment by jorana** [comment]
Fixed in #349
