### ISSUE TITLE
Move progressbar from get_iter

### ISSUE THREAD

**Issue by jorana** [AxFoundation/strax#354]
I think the progressbar (60 lines) makes `get_iter` a little convoluted:
https://github.com/AxFoundation/strax/blob/master/strax/context.py#L928

Perhaps we should try to make it a little simpler/transparent. It should not have be such complicated part of the code. It may well go into it's own function.

I think it could be as easy as just a wrapper around the function that you otherwise replace by a dummy wrapper.

**Comment by WenzDaniel** [comment]
Sure, I kind of agree. Do you have any suggestions?
