### ISSUE TITLE
Allow numpy>1.19

### ISSUE THREAD

**Issue by ershockley** [AxFoundation/strax#368]
Right now strax requires `numpy<=1.19, >=1.18.5`. It would be nice if it supported numpy>1.19 so that it can be used with tensorflow 2.4.0: `tensorflow 2.4.0 depends on numpy~=1.19.2`

**Comment by jorana** [comment]
Hi Evan, I tried this but it caused quite some issues:
https://github.com/AxFoundation/strax/commit/03ef8540ea361d13e9e182b196c2e8f4be4abb50
https://github.com/AxFoundation/strax/commit/03ef8540ea361d13e9e182b196c2e8f4be4abb50

Also caused some gray hair on straxen:
![afbeelding](https://user-images.githubusercontent.com/22295914/102659607-f90a9280-4179-11eb-9837-c79f3d600a7f.png)

Admittedly, this seems to at least partially seem to stem from our `tensorflow==2.3.1` requirement. Will put it on the to do list but there is a reason why we had to put that in.

**Comment by ershockley** [comment]
Hi Joran, so are these travis issues the reason for the numpy version limits? It's not something in the strax code itself? 

It looks like the problem in the build you linked was numpy 1.20 requires python 3.7. But what about e.g, 1.19.x? We also will be updating base env soon so maybe could drop py36 support anyway.

**Comment by jorana** [comment]
fixed in #369
