### ISSUE TITLE
dt integer overflow

### ISSUE THREAD

**Issue by jorana** [AxFoundation/strax#397]
We should add some test that the dt field can be stored in the int16. We either need to change the int16->int32 for everything or need to come up with some other smart solution. Effectively we cannot have peaks > 7ms due to this.

**Comment by JelleAalbers** [comment]
Changing peak(let)s `dt` to `int32` sounds great to me, and would make overflows nearly unthinkable. Let me just point out a related, though curious, three-year old comment here: https://github.com/AxFoundation/strax/blob/master/strax/processing/peak_building.py#L38...

 `find_peaks` originally had a `max_duration` argument, and promised to automatically break up peaks if their length got beyond sane values. Unfortunately I never implemented the code for this breaking-up. Later in https://github.com/AxFoundation/strax/issues/188, I noticed the unused `max_duration` argument and removed it, apparently forgetting the reason for adding it. I wrote that "We can add support for it when we find out we need it" -- perhaps that time has come :-)

(MergedS2s does still have a max_duration like check, it won't merge peaklets if the result would become larger than 15 us: https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L507)

**Comment by jorana** [comment]
Hi @JelleAalbers , of course, the question is very valid what we could gain science wise from allowing long wfs > 7 ms, down sample that to 200 samples and you have basically smeared out so much from the original features that you might not be able to see anything interesting anymore.

For straxen, either way would require a reprocessing of peaklets (unless we are going to set the max-time exactly at the int-overflow boundary for straxen where we know we cannot have data anyway) so I'm not sure what would make more sense.

**Comment by jorana** [comment]
For bookkeeping, see https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:commissioning:telecons:20210126#updates_on_daq

**Comment by jorana** [comment]
@WenzDaniel @darrylmasson @JelleAalbers 

I've opened two PRs  #420, and  #403 which both solve this problem in a different manner. Perhaps #420 (as per @JelleAalbers 's suggestion) is the easiest way forward as it prevents peaks > 6.7 ms ever being written.

Perhaps it is easier to discuss in this thread which option you consider better. I would be slightly inclined towards #420 , what are your ideas?

**Comment by JelleAalbers** [comment]
Thanks Joran; are your ideas mutually exclusive? A `max_duration` option seems like a nice addition even if the max peak length would be int32, and the extra storage byte (that will probably be mostly compressed away) seems a small price to pay for the comfort of never worrying about negative peak lengths again (maybe someone would like to try processing without max_duration at some point).

**Comment by jorana** [comment]
@JelleAalbers , valid point, especially if someone makes a (much) longer datafield, this might happen sooner. 

They are certainly not mutually exclusive, adding both is certainly also an option.
