### ISSUE TITLE
Ignore underscore for `include_tags` in run selection

### ISSUE THREAD

**Issue by jingqiangye** [AxFoundation/strax#448]
In the run selection, by default, we ignore the underscore for the tags in the database, but not the underscore for `include_tags`. Should we make it consistent by applying `ignore_underscore` to both?

https://github.com/AxFoundation/strax/blob/0db788f72a5ca7ac02336a0beffc4868d9107693/strax/run_selection.py#L167-L170

**Comment by jorana** [comment]
@jingqiangye, indeed yeah we also noticed. This is already addressed in #445
