### ISSUE TITLE
corrections write function uses numpy without importing it

### ISSUE THREAD

**Issue by jmosbacher** [AxFoundation/strax#536]
**Describe the bug**
The corrections interface uses np.isnan [here](https://github.com/AxFoundation/strax/blob/5466cb4c15663f8b71cef1891cffd07438491ef8/strax/corrections.py#L193) but never imports numpy

**Expected behavior**
numpy should be imported in head of file

**Comment by JoranAngevaare** [comment]
fixed in #537
