### ISSUE TITLE
tests/test_hitlet.py test too stringent? 

### ISSUE THREAD

**Issue by JoranAngevaare** [AxFoundation/strax#539]
Master failed on https://github.com/AxFoundation/strax/runs/3787298221?check_suite_focus=true for `test_conditional_entropy(data, size_template_and_ind_max_template)` with:
```python
data = array([-3.8847911, -0.5546908, -0.5546908, -8.079916 ,  7.364694 ,
        7.378992 , -0.5546908, -0.5546908, -0.5546908], dtype=float32)
size_template_and_ind_max_template = [1, 0]
```

Perhaps `rtol` is too small?

**Comment by WenzDaniel** [comment]
Hmm sure, if this starts to become an issue we can loosen the tolerance a bit. I have a different question though Since currently our tests are passing, I was always in the belief hypothesis would retry a certain test if it failed in the past. Is this only true for tests run locally?

**Comment by WenzDaniel** [comment]
Are you fine with observing the situation a bit before loosing the test? If so feel free to close.

**Comment by JoranAngevaare** [comment]
@WenzDaniel can you have a look:
https://github.com/AxFoundation/strax/runs/4758294267?check_suite_focus=true

**Comment by WenzDaniel** [comment]
Sure let me loosen the test requirement a bit.
