### ISSUE TITLE
Extra requirements in xenon plugins

### ISSUE THREAD

**Issue by coderdj** [AxFoundation/strax#56]
Right now keras is a requirement in the xenon plugins but not in base strax. I was going to make an addition to requirements.txt, but if we want to split the xenon plugins off maybe we want to put a requirements.txt in the strax/xenon folder as placeholder until that happens?

I'd anticipate more requirements coming from xenon-specific plugins as we develop more advanced reconstruction there so should organize this in an easy way to keep dependencies separate.

Edit: also tensorflow

**Comment by tunnell** [comment]
If you do pip install locally, there is a place in setup.py to add special requirements.  E.g. pip install strax[daq] I think.

**Comment by JelleAalbers** [comment]
Yes, right now it is strax[xenon], see https://github.com/AxFoundation/strax/blob/master/setup.py#L31. In the near future the xenon stuff will be split off to a separate repo, so this shouldn't be necessary anymore.

**Comment by coderdj** [comment]
Ah perfect, did not notice that.
