### ISSUE TITLE
Increased memory usage in make multi-run

### ISSUE THREAD

**Issue by WenzDaniel** [AxFoundation/strax#563]
**Describe the bug**
Currently there is a larger memory use by
```
 st.make(run_ids, data_type)
```
compared to 
```
for run in run_ids:
     st.make(run, data_type)
```
The problem arises from the fact that the result in the worker processes might not get garbage collected. <s>The issue is described also in https://stackoverflow.com/questions/54108434/garbage-collecting-python-subprocesses, but currently there is not much we can do about it. </s>

**Comment by JoranAngevaare** [comment]
Fixed in #581?
