### ISSUE TITLE
DAQ Veto Cut not working in combination with superruns

### ISSUE THREAD

**Issue by HenningSE** [AxFoundation/strax#583]
**Describe the bug**
When trying to load data along with the `daq_veto_cut`, `st.make` will not finish if `st.set_context_config({'write_superruns': True})` is used. If `st.make` is stopped via keyboardinterrupt the run can be loaded afterwards without problems. 

**To Reproduce**
The context is set up like this:
```python
st = cutax.xenonnt_v5(output_folder="/path/to/my/data",
                      cuts_for=['science_run_0.krypton_selections', 'commissioning.commissioning_cuts']
                     )

st.set_context_config({'write_superruns': True})
```
Then try to load data:
```python
st.make("some_run_id", "cut_daq_veto", progress_bar=True)
```
This can then be interrupted since the code is not finishing. When now running this again it works fine and the cut data can be loaded:
```python
st.make("some_run_id", "cut_daq_veto", progress_bar=True)
data = st.get_df("some_run_id", "cut_daq_veto")
```

If `st.set_context_config({'write_superruns': True})` the cut can be processed and loaded without problems. 

**Versions**
```
python	v3.8.12	
strax	v1.1.0	
straxen	v1.1.1	
cutax	v0.2.1	
```

**Comment by JoranAngevaare** [comment]
thanks @HenningSE for filling the issue. @WenzDaniel can you have a look? I think this is a key clue:
>If st.set_context_config({'write_superruns': True}) the cut can be processed and loaded without problems.

@HenningSE  perhaps it would help if you have an example run-id?

**Comment by HenningSE** [comment]
I tested it with calibration data. You could try e.g. run `21461`.

**Comment by WenzDaniel** [comment]
This is a side effect of the following bug: https://github.com/AxFoundation/strax/pull/562 Which is already fixed but only for strax master.
