### ISSUE TITLE
type difference between super runs and classic runs

### ISSUE THREAD

**Issue by DonNabla** [AxFoundation/strax#589]
**Describe the bug**
The type of `start`, `end` and `livetime` for a superruns are differents with respect to a classic run in strax (v1.1.1).

**To Reproduce**
If you create a superrun:
`st.define_run('_superrun_test', Run_list)`

and then look a the run database and compare superrun and basic run like below:

```
allruns = st.select_runs()
superuns = allruns[allruns.name.str.contains("_superrun_*") ]
basicruns = allruns[~allruns.name.str.contains("_superrun_*") ]

superuns.start.values[0]
superuns.end.values[0]
superuns.livetime.values[0]

basicruns.start.values[0]
basicruns.end.values[0]
basicruns.livetime.values[0]
```

We can see that for `start` and `end` the types are differents:

superruns -> Timestamp('XXXX-XX-XX XX:XX:XX.XXXXXX+XXXX', tz='<bson.tz_util.FixedOffset object at 0x7fd7cfa6e340>')
basicruns -> Timestamp('XXXX-XX-XX XX:XX:XX.XXXXXX')

Furthermore the livetime type in superruns is a `float`, while in a basic run it is `Timedelta`

**Expected behavior**
Both superruns and basic runs should have the same type for those variables otherwise it leads to some conflict especially if you want to apply boolean tests on time variables.

**Versions**
strax v1.1.1

**Comment by WenzDaniel** [comment]
Will be solved in https://github.com/AxFoundation/strax/pull/593.

**Comment by WenzDaniel** [comment]
Ubs, that was to early, lets close it when it is merged.
