### ISSUE TITLE
Strax does not wait for is_ready to process plugins

### ISSUE THREAD

**Issue by coderdj** [AxFoundation/strax#60]
Or it does, but just 2 seconds. This makes problems when using strax as a trigger where it's processing files as they come in. Strax waits the 2 seconds, then gets impatient and crashes itself because the file it wants still doesn't exist. 

See here: https://github.com/AxFoundation/strax/blob/v0.3.0/strax/plugin.py#L183

At the moment I fixed this by changing if --> while on L184 and adding a timeout. I can make a PR, but it's also possible I'm misunderstanding the main program loop since I could have sworn this was working in previous versions and doesn't seem to have changed recently.  

Side note: there doesn't really seem to be documentation on the core functionality, including the mailbox system.

**Comment by JelleAalbers** [comment]
Oops, yes, that used to be a while, but it somehow got messed up.

The docs are indeed still basic, what we have is here: https://strax.readthedocs.io/en/latest/ but there's a missing intermediate level, in between tutorials for end users and notes explaining deep development choices.

**Comment by tunnell** [comment]
@coderdj make PR?

**Comment by JelleAalbers** [comment]
Should be fixed now, let me know if not.
