### ISSUE TITLE
Frontend questions (dead code?)

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#65]
When are these ever called?
```
    def run_metadata(self, run_id):
        """Return run metadata dictionary, or raise RunMetadataNotAvailable"""
        raise NotImplementedError

    def write_run_metadata(self, run_id, metadata):
        """Stores metadata for run_id. Silently overwrites any previously
        stored run-level metadata."""
        raise NotImplementedError
```

Never I guess?  Can these be removed for now?  Or is this a place holder for the rundb?

**Comment by JelleAalbers** [comment]
They are indeed for metadata we are storing in the runs db now. We certainly want a `get_run_metadata` method in `Context` that will call `StorageFrontend.run_metadata`, and probably a similar one for the writer, but these are indeed missing at the moment. 

Another point is that maybe we don't want every backend to store this data, or at least all backends are not equal in this regard. The runs db is the master location for run-level metadata and has priority over some old csv file from a year ago.

**Comment by tunnell** [comment]
But they do nothing now
