### ISSUE TITLE
`Plugin.__version__` and `Plugin.version` are ambigous

### ISSUE THREAD

**Issue by JoranAngevaare** [AxFoundation/strax#688]
`Plugin.__version__` is used where `Plugin.version` should be used. Examples:
- [L2021](https://github.com/AxFoundation/strax/blob/a0d51fdd3bea52c228c8f74c614fc77bb7cf1bc5/strax/context.py#L2021)
- [L549](https://github.com/AxFoundation/strax/blob/a0d51fdd3bea52c228c8f74c614fc77bb7cf1bc5/strax/context.py#L549)
- [L695](https://github.com/AxFoundation/strax/blob/a0d51fdd3bea52c228c8f74c614fc77bb7cf1bc5/strax/context.py#L695)

After writing #690, I'm starting to seriously doubt the usefulness of having a `version` that depends on the `run_id` (which isn't even generated from the `Plugin.run_id` attribute).

**Comment by WenzDaniel** [comment]
Yes I think having run_id dependent versions does not make any sense anymore. To me https://github.com/AxFoundation/strax/blob/a0d51fdd3bea52c228c8f74c614fc77bb7cf1bc5/strax/plugin.py#L237-L243 looks like some legacy code and with CMT2.0 certainly not required anymore.

**Comment by WenzDaniel** [comment]
But I am wondering if we should not try to be consistent in our code and either use always `__version__` or `.version()`. I would be in favor of the former. If we do the later we might want to make it a  property.

**Comment by JoranAngevaare** [comment]
> But I am wondering if we should not try to be consistent in our code and either use always
Right, this issue is precisely about this 😉

I would also be in favor of dropping  the `version` class method (see my later addendum to this issue). I'm not super thrilled about this PR: https://github.com/AxFoundation/strax/pull/690. I can make https://github.com/AxFoundation/strax/pull/689 still work easily if we drop the `.version`-method by setting the `__getattr__` method appropriately.

My main issue is that the `version` method can now contain all kinds of weird code, which requires you to init the plugin in order to know what the version is going to be, which is slow. Making it a classmethod would already help.
