### ISSUE TITLE
Key naming

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#69]
Currently, the unique key for data is:

`170324_1748_event_basics_46c6d5c781c13c76a6d3a171d959f2673b4e8e1a`

However, the underscores are used both in the run name and also the key.  Can we switch to `-` to join these so they split() better? i.e.:

`170324_1748-event_basics-46c6d5c781c13c76a6d3a171d959f2673b4e8e1a`

**Comment by JelleAalbers** [comment]
Good idea; we could also use colons or other separators, but underscores are too overloaded. In general strax's requirements on the run_id are a bit weird / to strict at the moment, it's supposed to be a string that can be converted to an int..

**Comment by tunnell** [comment]
Done
