### ISSUE TITLE
Exception handling by snax/data management tool

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#75]
The multiprocessing makes it quite difficult to catch certain types of exceptions.  If I would want to implement checks to flag data with issues, I have to parse MailboxError strings and it gets messy.  Also, I end up not seeing all the exceptions.

https://gist.github.com/tunnell/c10bbf930a7e0e01cceac79554dd39b3

What would be best way to go about this?

**Comment by JelleAalbers** [comment]
Exceptions are propagated by #87, does that address the issue?

**Comment by JelleAalbers** [comment]
If you still encounter problems in the exception handling, feel free to reopen.
