### ISSUE TITLE
Interaction objects like in pax

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#83]
At the moment, we don't have interactions.  If we have a long event, there could be two interactions in it.  Or if we delayed-coincidence analysis.  Right now take main S2, then search for S1.  No loop over second largest S2 etc to see if reasonable S1 there too.  We do interaction[0] in pax jargon.

**Comment by JelleAalbers** [comment]
This should probably be an issue for straxen now, right?

**Comment by tunnell** [comment]
Could.... imagine other detectors might want it to if could frame it correctly.  Close for now
