### ISSUE TITLE
Check if all `argsort` use `mergesort`

### ISSUE THREAD

**Issue by dachengx** [AxFoundation/strax#916]
We must ensure that the `numpy.argsort` gives deterministic results, as well as in https://github.com/XENONnT/straxen.

This issue is closely related to https://github.com/XENONnT/straxen/pull/1176.

**Comment by yuema137** [comment]
I checked the source code of `numpy` and confirmed that `argsort` is a more fundamental method while `sort` is a higher-level API based on it. The algorithms are defined in cpp files like https://github.com/numpy/numpy/blob/main/numpy/_core/src/npysort/mergesort.cpp

With the `mergesort` method, the relative order is preserved:
https://github.com/numpy/numpy/blob/020e78cc3a4c7283bbe83290f0be5de3bc842f07/numpy/_core/src/npysort/mergesort.cpp#L67

So as long as we use `mergesort` I think we are good here.

**Comment by dachengx** [comment]
> So as long as we use `mergesort` I think we are good here.

Yes! So would you check whether we always use `mergesort`?

**Comment by yuema137** [comment]
Solved in #918
